-- 1. Create the facilities table
CREATE TABLE IF NOT EXISTS public.facilities (
    ref TEXT PRIMARY KEY,
    name_ar TEXT NOT NULL,
    name_fr TEXT NOT NULL,
    type TEXT NOT NULL,
    city_ar TEXT NOT NULL,
    city_fr TEXT NOT NULL,
    status TEXT NOT NULL,
    expiry_date DATE NOT NULL,
    legislation_ref TEXT,
    logo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Create the news table
CREATE TABLE IF NOT EXISTS public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_ar TEXT,
    title_fr TEXT,
    desc_ar TEXT,
    desc_fr TEXT,
    tag_ar TEXT,
    tag_fr TEXT,
    image_url TEXT,
    date_ar TEXT,
    date_fr TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create the page_content table
CREATE TABLE IF NOT EXISTS public.page_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_key TEXT UNIQUE NOT NULL,
    content JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- --- Enable Row Level Security (RLS) ---
ALTER TABLE public.facilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.page_content ENABLE ROW LEVEL SECURITY;

-- --- Create policies to allow public access (Simplified for development) ---

-- Facilities Policies
CREATE POLICY "Allow all on facilities" ON public.facilities FOR ALL USING (true) WITH CHECK (true);

-- News Policies
CREATE POLICY "Allow all on news" ON public.news FOR ALL USING (true) WITH CHECK (true);

-- Page Content Policies
CREATE POLICY "Allow all on page_content" ON public.page_content FOR ALL USING (true) WITH CHECK (true);
